name: run job on diff nodes
on: [push]
jobs:
  node-ver:
   runs-on: ubuntu-latest
   steps:
    - name: node version
      run: node -v
    - uses: action/setup-node@v1
      with:
        node-version: 6
    - name: node version is
      run: node -v
     
