name: run job on diff nodes
on: [push]
jobs:
  node-ver1:
   runs-on: ubuntu-latest
   steps:
    - name: node version
      run: node -v
    - uses: actions/setup-node@v1
      with:
        node-version: 6
    - name: node version is
      run: node -v
     
  node-ver2:
   runs-on: ubuntu-latest
   steps:
    - name: node version
      run: node -v
    - uses: actions/setup-node@v1
      with:
        node-version: 7
    - name: node version is
      run: node -v
